-- NdooHlcc V3.8 — tambahan schema Supabase
-- Jalankan sekali di Supabase SQL Editor.

create table if not exists public.stories (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  media_url text not null,
  media_type text not null,
  caption text default '',
  created_at timestamptz default now()
);

alter table public.stories enable row level security;

drop policy if exists "stories_read" on public.stories;
drop policy if exists "stories_create_own" on public.stories;
drop policy if exists "stories_delete_own" on public.stories;

create policy "stories_read"
on public.stories for select to authenticated using (true);

create policy "stories_create_own"
on public.stories for insert to authenticated
with check (user_id = auth.uid());

create policy "stories_delete_own"
on public.stories for delete to authenticated
using (user_id = auth.uid());

-- Notifications dibuat oleh aplikasi atas nama user yang sedang login.
drop policy if exists "notifications_create_actor" on public.notifications;
create policy "notifications_create_actor"
on public.notifications for insert to authenticated
with check (actor_id = auth.uid());

-- Indeks dasar agar feed/sosial tetap ringan ketika user mulai banyak.
create index if not exists posts_created_at_idx on public.posts (created_at desc);
create index if not exists comments_post_id_idx on public.comments (post_id, created_at);
create index if not exists follows_following_id_idx on public.follows (following_id);
create index if not exists favorites_user_id_idx on public.favorites (user_id);
create index if not exists notifications_user_read_idx on public.notifications (user_id, read, created_at desc);
create index if not exists messages_pair_idx on public.messages (sender_id, receiver_id, created_at);
create index if not exists stories_created_at_idx on public.stories (created_at desc);
